<?php

namespace Test;

use PHPUnit\Framework\TestCase;
use Muzik\OmnipayEsafe\CashOnDeliveryGateway;
use Muzik\OmnipayEsafe\Message\CompletePurchaseRequest;
use Muzik\OmnipayEsafe\Message\AcceptNotificationRequest;

class CashOnDeliveryGatewayTest extends TestCase
{
    protected CashOnDeliveryGateway $gateway;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->gateway = new CashOnDeliveryGateway();
    }

    public function test_supports_apis()
    {
        $this->assertFalse($this->gateway->supportsAuthorize());
        $this->assertFalse($this->gateway->supportsCompleteAuthorize());
        $this->assertFalse($this->gateway->supportsCapture());
        $this->assertFalse($this->gateway->supportsPurchase());
        $this->assertTrue($this->gateway->supportsCompletePurchase());
        $this->assertFalse($this->gateway->supportsRefund());
        $this->assertFalse($this->gateway->supportsVoid());
        $this->assertTrue($this->gateway->supportsAcceptNotification());
        $this->assertFalse($this->gateway->supportsCreateCard());
        $this->assertFalse($this->gateway->supportsDeleteCard());
        $this->assertFalse($this->gateway->supportsUpdateCard());
    }

    public function test_set_api_key()
    {
        $this->gateway->setApiKey('abcd5888');

        $this->assertSame('abcd5888', $this->gateway->getApiKey());
    }

    public function test_set_api_key_when_initialize()
    {
        $this->gateway->initialize(['api_key' => 'abcd5888']);

        $this->assertSame('abcd5888', $this->gateway->getApiKey());
    }

    public function test_complete_purchase()
    {
        $this->gateway->setApiKey('abcd5888');
        $request = $this->gateway->completePurchase([
            'buysafeno' => '2400009912300000019',
            'web' => 'S1103020010',
            'Td' => '',
            'MN' => '1000',
            'Name' => 'V****** **i',
            'note1' => '',
            'note2' => '',
            'SendType' => '1',
            'errcode' => '00',
            'CargoNo' => 'F23501480823',
            'InvoiceNo' => '',
            'ChkValue' => '6E0ED343525CDCBE678BB1103054CBA25E634282',
        ]);

        $this->assertInstanceOf(CompletePurchaseRequest::class, $request);
    }

    public function test_accept_notification()
    {
        $this->gateway->setApiKey('abcd5888');
        $request = $this->gateway->acceptNotification([
            'buysafeno' => '2400009912300000019',
            'web' => 'S1103020010',
            'MN' => '1000',
            'Td' => '',
            'webname' => '英屬維京群島商希幔數位有限公司台灣分公司',
            'Name' => 'V****** **i',
            'note1' => '',
            'note2' => '',
            'ApproveCode' => '',
            'Card_NO' => '',
            'Card_Type' => '',
            'UserNo' => '',
            'PayDate' => '',
            'PayTime' => '',
            'SendType' => '1',
            'errcode' => '',
            'errmsg' => '',
            'paycode' => '',
            'PayType' => '',
            'PayAgency' => '',
            'PayAgencyMemo' => '',
            'PayAgencyName' => '',
            'PayAgencyTel' => '',
            'PayAgencyAddress' => '',
            'BarcodeA' => '',
            'BarcodeB' => '',
            'BarcodeC' => '',
            'PostBarcodeA' => '',
            'PostBarcodeB' => '',
            'PostBarcodeC' => '',
            'EntityATM' => '',
            'BankCode' => '',
            'BankName' => '',
            'CargoNo' => 'F23501480823',
            'StoreName' => '統一取貨用',
            'StoreID' => '167606',
            'InvoiceNo' => '',
            'tokenData' => '',
            'ChkValue' => '7EBA96AA5FAEBC72E48A284C74840E81D5B4B5FA',
        ]);

        $this->assertInstanceOf(AcceptNotificationRequest::class, $request);
    }
}
